// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrqVvQ7gX8N_3M0RgSum9n6e6Y7n_SfGg',
    appId: '1:545892045661:web:bfa186b6238d2762a18eb4',
    messagingSenderId: '545892045661',
    projectId: 'diaryapp-3df79',
    authDomain: 'diaryapp-3df79.firebaseapp.com',
    storageBucket: 'diaryapp-3df79.appspot.com',
    measurementId: 'G-2MR1BB7V5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHJblR_ncjuI7dVh3iHRLGVeyBLmLVByI',
    appId: '1:545892045661:android:abca3cb367600684a18eb4',
    messagingSenderId: '545892045661',
    projectId: 'diaryapp-3df79',
    storageBucket: 'diaryapp-3df79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHv_eUQe1CsGGLEAhtMRgdGKvqOmPFthw',
    appId: '1:545892045661:ios:66f58a2a1c923eeea18eb4',
    messagingSenderId: '545892045661',
    projectId: 'diaryapp-3df79',
    storageBucket: 'diaryapp-3df79.appspot.com',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHv_eUQe1CsGGLEAhtMRgdGKvqOmPFthw',
    appId: '1:545892045661:ios:f07547f8f79f0983a18eb4',
    messagingSenderId: '545892045661',
    projectId: 'diaryapp-3df79',
    storageBucket: 'diaryapp-3df79.appspot.com',
    iosBundleId: 'com.example.diaryapp.RunnerTests',
  );
}
